"""Alembic migration 回归。

锁四件事(对应 Schema §7 红线):
1. `upgrade head` 能跑通(本身就是冒烟);
2. `downgrade base` 能干净反向(reversible 红线 #5);
3. ORM ↔ DDL 无漂移(`compare_type=True` + `compare_server_default=True`
   下 autogen 应找不到 diff);
4. 我们关心的 DB 实体确实落了:3 个扩展、7 个 `updated_at` 触发器、
   CHECK 约束生效、pgvector 列类型是 `vector`(而不是 BYTEA 或别的退化)。

为啥这些都得测:
- autogen **盲信**会漏 CHECK / 部分索引 / pgvector / 触发器(Schema §7 红线 2);
- 单元测试不能依赖"alembic check 通过 = schema 正确" —— 必须直接查 PG
  catalog(`pg_extension` / `pg_trigger` / `pg_attribute`)+ 跑实际 INSERT
  让 PG 自己说话。

本文件不用 `db_session`(SAVEPOINT 隔离),因为我们就是要测 schema 层;
直接用 session-scoped `engine` 跑只读查询 / 临时 connection 跑写入测试。
"""

from __future__ import annotations

from pathlib import Path

import pytest
from sqlalchemy import text
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncEngine
from testcontainers.postgres import PostgresContainer

from alembic import command
from alembic.config import Config
from tests.conftest import _run_in_thread


def _make_cfg(sync_url: str) -> Config:
    """造一个绑定到指定 sync URL 的 alembic Config(用于命令行式调用)。"""
    backend_root = Path(__file__).resolve().parent.parent
    cfg = Config(str(backend_root / "alembic.ini"))
    cfg.set_main_option("script_location", str(backend_root / "alembic"))
    cfg.set_main_option("sqlalchemy.url", sync_url)
    return cfg


def _sync_url_from_container(pg: PostgresContainer) -> str:
    """testcontainers 给的 URL 可能带 `+psycopg2` / `+psycopg` 后缀,
    alembic env.py 自己升级 async,这里要 plain sync 形态。
    """
    url = pg.get_connection_url()
    for prefix in ("postgresql+psycopg2://", "postgresql+psycopg://"):
        if url.startswith(prefix):
            return url.replace(prefix, "postgresql://", 1)
    return url


@pytest.mark.asyncio
async def test_upgrade_head_succeeds(engine: AsyncEngine) -> None:
    """`engine` fixture 已经跑过 upgrade head;只要 fixture 没崩,本测试就是绿。

    再额外查 `alembic_version` 表确认 head revision 已写入(防止 fixture
    悄悄吞异常)。
    """
    async with engine.connect() as conn:
        result = await conn.execute(text("SELECT version_num FROM alembic_version"))
        row = result.first()
    assert row is not None, "alembic_version 表应当有一条记录"
    assert row[0] == "0001_init"


@pytest.mark.asyncio
async def test_downgrade_base_succeeds(pg_container: PostgresContainer, engine: AsyncEngine) -> None:
    """验 downgrade 干净反向,然后 upgrade 回 head 不污染后续测试。

    关键执行顺序(且 try/finally 兜底,避免中间步骤异常导致 schema 半残留):
    1. downgrade base   —— 13 表全 drop
    2. SELECT pg_tables —— 用 session-scoped async engine(不引 psycopg2,见 D8),
                            注意此时表都没了,只能查 pg_tables 这种 catalog
    3. upgrade head     —— **finally 块里**,无论 2 是否抛都要恢复;否则后续测试
                            全炸 "relation users does not exist"

    我们直接复用 session-scoped `engine`(已绑同一 PG container);用单独 engine
    会再开一个连接池,可能与 alembic 的 NullPool 抢端口,本身没必要。
    """
    sync_url = _sync_url_from_container(pg_container)
    cfg = _make_cfg(sync_url)

    # 用 thread 隔离避免 env.py 的 asyncio.run 撞 pytest loop
    _run_in_thread(command.downgrade, cfg, "base")
    try:
        async with engine.connect() as conn:
            result = await conn.execute(
                text(
                    "SELECT tablename FROM pg_tables "
                    "WHERE schemaname = 'public' AND tablename != 'alembic_version'"
                )
            )
            remaining = [r[0] for r in result]
        assert remaining == [], f"downgrade 后还剩表:{remaining}"
    finally:
        # 恢复 schema —— 即便上面 assert 失败也要 upgrade 回去,避免污染后续用例
        _run_in_thread(command.upgrade, cfg, "head")


@pytest.mark.asyncio
async def test_autogen_no_pending_diff(
    pg_container: PostgresContainer, engine: AsyncEngine
) -> None:
    """跑 `alembic check`(等价于 autogen → 看是否产生新 op),确认 ORM 与 DDL 同步。

    这是 Schema §7 红线 #2 的核心防线之一:如果将来有人改了 Model 但没生成
    新 revision,这里会失败。注意:autogen 仍会漏 CHECK / 部分索引 / 触发器,
    所以这只是必要条件而非充分条件 —— 还需要 `test_check_constraints_users_role`
    / `test_triggers_created` 等用例配合。

    依赖 `engine` fixture(虽然本测试不直接用 engine 对象):因为 engine 启动时
    跑过 `upgrade head`,确保 DB 是 head 状态;否则 alembic check 会抛
    "Target database is not up to date"(autogen 的前置要求)。
    """
    del engine  # 仅取 fixture 副作用(预先 upgrade 到 head),不直接使用对象
    sync_url = _sync_url_from_container(pg_container)
    cfg = _make_cfg(sync_url)

    # `alembic check` 在有 pending diff 时抛 AutogenerateDiffsDetected
    # 我们用 try/except 把异常翻译成 assert 失败,而不是让测试以 ERROR 收场
    # 用 thread 隔离避免 env.py 的 asyncio.run 撞 pytest loop
    try:
        _run_in_thread(command.check, cfg)
    except Exception as exc:
        # alembic 1.14 抛 alembic.util.exc.AutogenerateDiffsDetected
        pytest.fail(f"ORM/DDL 有未落地 diff:{exc!s}")


@pytest.mark.asyncio
async def test_extensions_created(engine: AsyncEngine) -> None:
    """3 个必装扩展(Schema §2.1)都得在 pg_extension 里。"""
    async with engine.connect() as conn:
        result = await conn.execute(text("SELECT extname FROM pg_extension"))
        installed = {row[0] for row in result}
    for required in ("uuid-ossp", "pg_trgm", "vector"):
        assert required in installed, f"扩展 {required} 缺失,实际:{installed}"


@pytest.mark.asyncio
async def test_triggers_created(engine: AsyncEngine) -> None:
    """7 张表(Schema §5.5)各挂一个 `trg_<table>_updated_at` 触发器。"""
    expected = {
        "trg_users_updated_at",
        "trg_cases_updated_at",
        "trg_ocr_results_updated_at",
        "trg_ai_reports_updated_at",
        "trg_knowledge_files_updated_at",
        "trg_import_jobs_updated_at",
        "trg_admin_reviews_updated_at",
    }
    async with engine.connect() as conn:
        result = await conn.execute(text("SELECT tgname FROM pg_trigger WHERE NOT tgisinternal"))
        actual = {row[0] for row in result}
    missing = expected - actual
    assert not missing, f"触发器缺失:{missing}(实际:{actual})"


@pytest.mark.asyncio
async def test_check_constraints_users_role(engine: AsyncEngine) -> None:
    """CHECK 约束直接用 PG 行为验证(autogen 漏 CHECK 的兜底)。

    `users.role` 必须是合法枚举值(free_user / paid_user / super_admin);
    插入 `'bad'` 应触发 IntegrityError。同时插入一个合法值确认放行。
    """
    async with engine.begin() as conn:
        await conn.execute(
            text(
                "INSERT INTO users (phone, role, status) " "VALUES (:phone, 'free_user', 'active')"
            ),
            {"phone": "13800000001"},
        )

    # 非法 role 应被 CHECK 拒
    with pytest.raises(IntegrityError):
        async with engine.begin() as conn:
            await conn.execute(
                text(
                    "INSERT INTO users (phone, role, status) "
                    "VALUES (:phone, 'bad_role', 'active')"
                ),
                {"phone": "13800000002"},
            )

    # 清理本测试插的数据,避免影响后续 smoke 测试的计数
    async with engine.begin() as conn:
        await conn.execute(text("DELETE FROM users WHERE phone = '13800000001'"))


@pytest.mark.asyncio
async def test_pgvector_column_present(engine: AsyncEngine) -> None:
    """`cases.embedding` 必须是 `vector` 类型(autogen 会把 pgvector 退化成 BYTEA)。

    覆盖 cases / ai_reports / knowledge_files 三张表的 embedding 列。
    """
    expected_tables = ("cases", "ai_reports", "knowledge_files")
    # 关于 SQL:不用 `:tbl::regclass` 命名参数 + `::regclass` 强转的混合写法,
    # asyncpg 解析时会把第二个 `::` 误判成参数边界,产生 syntax error。
    # 表名是受控常量(不来自外部输入),直接拼字符串安全。
    async with engine.connect() as conn:
        for table in expected_tables:
            result = await conn.execute(
                text(
                    f"SELECT atttypid::regtype::text FROM pg_attribute "
                    f"WHERE attrelid = '{table}'::regclass AND attname = 'embedding'"
                )
            )
            row = result.first()
            assert row is not None, f"{table}.embedding 列不存在"
            assert row[0] == "vector", f"{table}.embedding 类型应为 vector,实际:{row[0]}"
